language: dart

sudo: required
addons:
  chrome: stable
branches:
  only:
    - master

script:
  - pub run build_runner build test
  - dartanalyzer .
  - dartfmt .

cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool/build