name: graphened
version: 0.0.2
description: >-
  A Dart library for Graphene&#x2F;Bitshares blockchain.
author: Pavel Kozlovskiy <pavel2033@gmail.com>
homepage: http://github.com/dart-lang/graphened
repository: https://github.com/pkozlovskiy/graphened

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^1.1.3
  json_serializable: ^2.2.1
  test: ^1.6.0